# GitHub Actions workflow for linting, testing, building, and publishing
# to npm and jsr using pnpm and package.json scripts

name: Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpx @biomejs/biome ci
      - run: pnpm test

  build-and-publish-npm:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write # https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write # OIDC token for JSR auth
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          package_json_file: 'package.json'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm publish:jsr
